export const AGENTS = [
  {
    id: 'resolve',
    name: 'CustodyQAI Resolve',
    subtitle: 'AI Settlement Exception Investigator',
    description: 'Assists operations analysts in investigating settlement exceptions such as SSI mismatches and payment breaks.',
    workflow: 'Exception → Evidence → Root Cause → Recommendation → Human Review → Resolution',
    status: 'Prototype',
    featured: 'First Product Demonstration',
  },
  {
    id: 'reconiq',
    name: 'ReconIQ',
    subtitle: 'AI Reconciliation Investigator',
    description: 'Explores how AI could investigate reconciliation breaks between internal books and custodian positions.',
    workflow: 'Break Detected → Evidence → Classification → Recommendation → Human Review',
    status: 'Concept',
  },
  {
    id: 'ca-intelligence',
    name: 'CA Intelligence',
    subtitle: 'AI Corporate Actions Analyst',
    description: 'Extracts and interprets corporate action announcements to identify operational impact and entitlements.',
    workflow: 'Notice → Extraction → Classification → Eligibility → Entitlement → Actions',
    status: 'Concept',
  },
  {
    id: 'ssi-guardian',
    name: 'SSI Guardian',
    subtitle: 'AI Standing Settlement Instruction Validator',
    description: 'Compares settlement instruction sources to flag potential SSI mismatches before settlement release.',
    workflow: 'Instruction Received → Comparison → Risk Detection → Recommendation → Human Review',
    status: 'Concept',
  },
  {
    id: 'messageiq',
    name: 'MessageIQ',
    subtitle: 'AI Intelligence for Operational Messages',
    description: 'Interprets operational messages to extract entities, required actions, and potential risk.',
    workflow: 'Message → Classification → Entity Extraction → Risk Flag → Next Step',
    status: 'Concept',
  },
  {
    id: 'exception-prioritizer',
    name: 'Exception Prioritizer',
    subtitle: 'AI-Powered Exception Command Center',
    description: 'Prioritizes open exceptions by risk, SLA proximity, and historical pattern — recommends, never executes.',
    workflow: 'Exceptions → Risk Scoring → SLA Analysis → Priority Ranking → Explanation',
    status: 'Concept',
  },
  {
    id: 'ops-knowledge',
    name: 'Ops Knowledge Agent',
    subtitle: 'Ask CustodyQAI',
    description: 'A knowledge-retrieval style agent that helps operations teams find relevant SOPs and historical cases.',
    workflow: 'Question → Retrieval → Structured Answer → Sources Cited',
    status: 'Concept',
  },
  {
    id: 'clientops-ai',
    name: 'ClientOps AI',
    subtitle: 'AI-Assisted Custody Client Servicing',
    description: 'Drafts client-ready responses to custody servicing queries for human review and approval before sending.',
    workflow: 'Client Query → Internal Analysis → Draft Response → Human Approval',
    status: 'Concept',
  },
];
